### ISSUE TITLE
Getting NoClassDefFoundError after fixing dependencies per quickstart

### ISSUE THREAD

**Issue by jimshowalter** [spring-cloud-incubator/spring-cloud-sleuth-otel#60]
Now everything builds and starts to run, but then we get:

java.lang.NoClassDefFoundError: io/opentelemetry/sdk/metrics/SdkMeterProvider
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.configureMeterProvider(OpenTelemetrySdkAutoConfiguration.java:55)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.api.GlobalOpenTelemetry.maybeAutoConfigure(GlobalOpenTelemetry.java:156)
	at io.opentelemetry.api.GlobalOpenTelemetry.get(GlobalOpenTelemetry.java:56)

Configuration is:

  implementation 'org.springframework.boot:spring-boot-starter-web:4.5.1'
  implementation 'org.springframework.cloud:spring-cloud-dependencies:2020.0.3'
  implementation 'org.springframework.cloud:spring-cloud-sleuth-otel-dependencies:1.0.0-M7'
  implementation('org.springframework.cloud:spring-cloud-starter-sleuth:3.0.3') {
    exclude group: 'org.springframework.cloud', module: 'spring-cloud-sleuth-brave'
  }
  implementation 'org.springframework.cloud:spring-cloud-sleuth-otel-autoconfigure:1.0.0-M7'

**Comment by jimshowalter** [comment]
https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java#L56

**Comment by jimshowalter** [comment]
Seems to be from implementation group: 'io.opentelemetry', name: 'opentelemetry-sdk-metrics', version: '1.3.0-alpha'

That's not on the classpath despite having the BOMs.

We do see io.opentelemetry:opentelemetry-api-metrics:1.0.3-alpha

**Comment by jimshowalter** [comment]
io.opentelemetry.sdk.autoconfigure.ConfigurationException: OTLP Metrics Exporter enabled but opentelemetry-exporter-otlp-metrics not found on classpath. Make sure to add it as a dependency to enable this feature.

Are we not supposed to use that exporter?

**Comment by marcingrzejszczak** [comment]
Why do you set both `starter-sleuth` and `cloud-dependencies` versions manually? Also those should be used as boms not as direct dependencies. Additionally please do not file an issue every time you have a hurdle because this is not a chat. If you want to have a conversation please go to the Gitter chat  https://gitter.im/spring-cloud/spring-cloud and the community will for sure help you out.
